server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "postgres"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: "15m"

ethereum:
  rpc: "https://sepolia.infura.io/v3/09e9e581f3fd47e8b590c0a627f96eed"
  chain_id: 11155111
  token_address: "0xe06343731baf7aA1c0dB9056FAe6969D4252B8d1"
