server:
  port:
  host:
  endpoint:
  websocket:
    ping_interval:
    write_wait:
    pong_wait:
    max_message_size:

database:
  host:
  port:
  user:
  password:
  name:
  sslmode:
  max_open_conns:
  max_idle_conns:
  conn_max_lifetime:
  url:

ethereum:
  rpc:
  chain_id:
  token_address:
  stake_wallet_address:

runner:
  server_url:
  websocket_url:
  api_prefix:
  poll_interval:
  docker:
    memory_limit:
    cpu_limit:
    timeout:
  ipfs:
    image:
    api_port:
    gateway_port:
    swarm_port:
    data_dir:

ipfs:
  api_url:

p2p:
  listen_addrs:
    - "/ip4/0.0.0.0/tcp/9000"
  bootstrap_peers:
    - "/ip4/123.45.67.89/tcp/9000/p2p/QmPeerID"
    - "/dns4/bootstrap.example.com/tcp/9000/p2p/QmOtherPeerID"
  subgroup:
    min_size:
    max_size:
  consensus:
    timeout:
    threshold:
